import ReduxProvider from '@/lib/ReduxProvider';
import './globals.css';
import {Inter} from 'next/font/google';

const inter = Inter({subsets: ['latin']});

export const metadata = {
  title: 'Netflix',
  description: 'Generated by create next app',
};

interface props {
  children: React.ReactNode;
};

function RootLayout({children}: props) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black`}>
        <ReduxProvider>
          <div>
            {children}
          </div>
        </ReduxProvider>
      </body>
    </html>
  );
};

export default RootLayout;